---
- name: Terminate all stopped EC2 instances dynamically
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:
    - name: Gather info about all runnig and stopped EC2 instances
      amazon.aws.ec2_instance_info:
        region: us-east-1
        filters:
          instance-state-name: running and stopped
      register: ec2_info

    - name: Terminate all gathered EC2 instances
      amazon.aws.ec2_instance:
        state: absent
        instance_ids: "{{ ec2_info.instances | map(attribute='instance_id') | list }}"
        region: us-east-1
        aws_access_key: "{{ ec2_access_key }}"
        aws_secret_key: "{{ ec2_secret_key }}"
      when: ec2_info.instances | length > 0

