---
- name: Install basic packages and services on AWS EC2 instances
  hosts: aws
  become: true

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install required packages
      apt:
        name:
          - nginx
          - docker.io
          - python3
          - wget
          - curl
        state: present

    - name: Enable and start nginx
      systemd:
        name: nginx
        enabled: true
        state: started

    - name: Enable and start Docker
      systemd:
        name: docker
        enabled: true
        state: started

    - name: Add ubuntu user to docker group
      user:
        name: ubuntu
        groups: docker
        append: yes

